// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA5cUyF7BlJo19k3iD_2GbukMlojc8iVA',
    appId: '1:202279690454:web:ec56a8a317e72e444f6977',
    messagingSenderId: '202279690454',
    projectId: 'chatmate-7761d',
    authDomain: 'chatmate-7761d.firebaseapp.com',
    storageBucket: 'chatmate-7761d.appspot.com',
    measurementId: 'G-V5PGJ3QCN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxDXmyQ8SF3V5afBpdXLlng6kQdKNjnvE',
    appId: '1:202279690454:android:fd99ddf3bffb3df44f6977',
    messagingSenderId: '202279690454',
    projectId: 'chatmate-7761d',
    storageBucket: 'chatmate-7761d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDToNik9eqMAikekr6_oNG17DiCi6FHTog',
    appId: '1:202279690454:ios:9507f6b3b233f1434f6977',
    messagingSenderId: '202279690454',
    projectId: 'chatmate-7761d',
    storageBucket: 'chatmate-7761d.appspot.com',
    iosBundleId: 'com.example.chatmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDToNik9eqMAikekr6_oNG17DiCi6FHTog',
    appId: '1:202279690454:ios:55dedd222f6a01614f6977',
    messagingSenderId: '202279690454',
    projectId: 'chatmate-7761d',
    storageBucket: 'chatmate-7761d.appspot.com',
    iosBundleId: 'com.example.chatmate.RunnerTests',
  );
}
